---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Code Base

env:
  MAIN_BRANCH: main
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      statuses: write
      contents: read
      packages: read

    steps:
      # https://github.com/ivuorinen/actions
      - uses: ivuorinen/actions/pr-lint@a09e59aa7cb8246f584764d33505ff861b4c240c # 25.10.24
