---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Code Base

env:
  MAIN_BRANCH: main
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      statuses: write
      contents: read
      packages: read

    steps:
      # https://github.com/ivuorinen/actions
      - uses: ivuorinen/actions/pr-lint@ff0ca4bc920c518b2ce2dc20c5e5a6e95f76dee0 # v2025.11.02
